//var plantId =
//var filename =
var plantName = "San Pedro"; 
var latinName = "Echinopsis Pachanoi";
var type = "Cactus";
var avgLifespan = 80; //Years
var waterCycle = 2; //Weeks 
var hardiness = "Hardy";
var avgHeight = 6; //Meters
var avgWidth = 1.8; //Meters
var growthRate = 0.3; //Meters p/year 
var climate = "Arid";
var origin = "Andes Mountains";
var edible = false;
var fact = "For thousands of years this cactus' flesh has been boiled down to create a traditional Andean medicine as it contains mescaline; a chemical said to induce an 8-12 hour hallucinogenic high.";

//var plantId =
//var filename =
var plantName = "Saguaro"; 
var latinName = "Carnegiea Gigantea";
var type = "Cactus";
var avgLifespan = 150; //Years
var waterCycle = 13; //Weeks 
var hardiness = "Hardy";
var avgHeight = 12; //Meters
var avgWidth = 3.1; //Meters
var growthRate = 0.05; //Meters p/year 
var climate = "Arid";
var origin = "Arizona, California, Sonora";
var edible = false;
var fact = "The tallest species of cactus, the tallest ever measuring 23.8m before being toppled over in a windstorm in 1986.";

//var plantId =
//var filename =
var plantName = "Golden Barrel"; 
var latinName = "Echinocactus Grusonii";
var type = "Cactus";
var avgLifespan = 100; //Years
var waterCycle = 8; //Weeks 
var hardiness = "Hardy";
var avgHeight = 1; //Meters
var avgWidth = 1; //Meters
var growthRate = 0.01; //Meters p/year 
var climate = "Arid";
var origin = "East Central Mexico";
var edible = false;
var fact = "This cactus grows in volcanic, rocky slopes and is endangered after the creation of a dam in their natural habitat in the 1990's.";

